CREATE TABLE `XXX_SEG_PERMISOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) DEFAULT NULL,
  `DESCRIPCION` varchar(300) DEFAULT NULL,
  `PERMISO_PADRE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

INSERT INTO `XXX_SEG_PERMISOS` VALUES (1,'Superadministrador','Superadministrador',NULL),(2,'Administración','Administración',1),(3,'Administración Roles','Administración de Roles',2);

CREATE TABLE `XXX_SEG_ROLES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  `DESCRIPCION` varchar(200) NOT NULL,
  `BAJA` tinyint(1) NOT NULL DEFAULT '0',
  `FECHA_MOD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

INSERT INTO `XXX_SEG_ROLES` VALUES (1,'ROL_ANONIMO','Rol que tendrán los usuarios por defecto',0,'2018-01-07 11:35:45'),(2,'ROL_SUPERADMIN','Superadministrador',0,'2018-01-07 11:35:45'),(3,'ROL_INICIO','Da permiso a mostrar el Menu inicio',0,'2018-01-07 11:35:45');

CREATE TABLE `XXX_SEG_ROLES_PERMISOS` (
  `ID_ROL` int(11) DEFAULT NULL,
  `ID_PERMISO` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `XXX_SEG_ROLES_PERMISOS` VALUES (2,1);

CREATE TABLE `XXX_SEG_USUARIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(120) NOT NULL,
  `LOGIN` varchar(20) NOT NULL,
  `PASSWORD` varchar(64) NOT NULL,
  `EMAIL` varchar(200) NOT NULL,
  `BAJA` tinyint(1) NOT NULL DEFAULT '0',
  `FECHA_MOD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO `XXX_SEG_USUARIOS` VALUES (1,'Administrador','admin','21232f297a57a5a743894a0e4a801fc3','admin@admin.es',0);

CREATE TABLE `XXX_SEG_USUARIOS_ROLES` (
  `ID_USUARIO` int(11) DEFAULT NULL,
  `ID_ROL` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `XXX_SEG_USUARIOS_ROLES` VALUES (1,1),(1,2),(1,3);